function data_partationed = partationing_64QAM(data_in,NormalValue,thr_I,thr_Q)
%

%
data_partationed = cell(64,1);
if nargin < 3
    thr_I=zeros(7,1);
for jj=1:7
    thr_I(jj)=-1+0.1429+0.1429*2*(jj-1);
end
    thr_Q=thr_I;
    thr_I = thr_I*NormalValue;
thr_Q = thr_Q*NormalValue;
end

for ii = 1: 8
    if ii==1
    data_partationed{8*ii-7} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)<thr_Q(1)));
data_partationed{8*ii-6} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)>thr_Q(1)) & (imag(data_in)< thr_Q(2)));
data_partationed{8*ii-5} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)> thr_Q(2)) & (imag(data_in)< thr_Q(3)));
data_partationed{8*ii-4} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)> thr_Q(3)) & (imag(data_in)< thr_Q(4)));
data_partationed{8*ii-3} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)> thr_Q(4)) & (imag(data_in)< thr_Q(5)));
data_partationed{8*ii-2} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)> thr_Q(5)) &(imag(data_in)< thr_Q(6)));
data_partationed{8*ii-1} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)> thr_Q(6)) &(imag(data_in)< thr_Q(7)));
data_partationed{8*ii} = ...
    data_in((real(data_in)<thr_I(1)) & ...
    (imag(data_in)> thr_Q(7)));
    elseif ii== 8
    data_partationed{8*ii-7} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)<thr_Q(1)));
data_partationed{8*ii-6} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)>thr_Q(1)) & (imag(data_in)< thr_Q(2)));
data_partationed{8*ii-5} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)> thr_Q(2)) & (imag(data_in)< thr_Q(3)));
data_partationed{8*ii-4} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)> thr_Q(3)) & (imag(data_in)< thr_Q(4)));
data_partationed{8*ii-3} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)> thr_Q(4)) & (imag(data_in)< thr_Q(5)));
data_partationed{8*ii-2} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)> thr_Q(5)) &(imag(data_in)< thr_Q(6)));
data_partationed{8*ii-1} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)> thr_Q(6)) &(imag(data_in)< thr_Q(7)));
data_partationed{8*ii} = ...
    data_in((real(data_in)>thr_I(7)) & ...
    (imag(data_in)> thr_Q(7)));    
    else
data_partationed{8*ii-7} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)<thr_Q(1)));
data_partationed{8*ii-6} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)>thr_Q(1)) & (imag(data_in)< thr_Q(2)));
data_partationed{8*ii-5} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)> thr_Q(2)) & (imag(data_in)< thr_Q(3)));
data_partationed{8*ii-4} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)> thr_Q(3)) & (imag(data_in)< thr_Q(4)));
data_partationed{8*ii-3} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)> thr_Q(4)) & (imag(data_in)< thr_Q(5)));
data_partationed{8*ii-2} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)> thr_Q(5)) &(imag(data_in)< thr_Q(6)));
data_partationed{8*ii-1} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)> thr_Q(6)) &(imag(data_in)< thr_Q(7)));
data_partationed{8*ii} = ...
    data_in((real(data_in)>thr_I(ii-1)) & (real(data_in)<thr_I(ii)) &...
    (imag(data_in)> thr_Q(7)));
    end
end

